version: '3.9'
services:
  api:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    command: sh -c "pnpm --filter @marketing-afiliados/api run build && pnpm --filter @marketing-afiliados/api run start"
    env_file:
      - ../../apps/api/.env.production
      - ../../.env.shared
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
      - redis
    ports:
      - "4701:3001"
    restart: unless-stopped

  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    command: sh -c "pnpm --filter @marketing-afiliados/web run build && pnpm --filter @marketing-afiliados/web run start"
    env_file:
      - ../../apps/web/.env.production
      - ../../.env.shared
    environment:
      NODE_ENV: production
    depends_on:
      - api
    ports:
      - "4700:3000"
    restart: unless-stopped

  worker:
    build:
      context: ../..
      dockerfile: apps/worker/Dockerfile
    command: sh -c "pnpm --filter @marketing-afiliados/worker run build && node apps/worker/dist/index.js"
    env_file:
      - ../../apps/worker/.env.production
      - ../../.env.shared
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: marketing_afiliados
      POSTGRES_USER: marketing
      POSTGRES_PASSWORD: marketing
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "4125:1025"
      - "9125:8025"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.52.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api
      - worker
    ports:
      - '9090:9090'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.5.2
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    ports:
      - '4790:3000'
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
