import Joi from 'joi';

export const validationSchema = Joi.object({
  PORT: Joi.number().default(3001),
  CORS_ORIGINS: Joi.string().allow('').optional(),
  JWT_ACCESS_SECRET: Joi.string().min(16).default('change-me-access'),
  JWT_REFRESH_SECRET: Joi.string().min(16).default('change-me-refresh'),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('3600s'),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),
  VTEX_ACCOUNT: Joi.string().allow('').default(''),
  VTEX_ENVIRONMENT: Joi.string().default('production'),
  VTEX_APP_KEY: Joi.string().allow('').default(''),
  VTEX_APP_TOKEN: Joi.string().allow('').default(''),
  VTEX_BASE_URL: Joi.string().allow('').optional(),
  VTEX_TIMEOUT_MS: Joi.number().integer().min(100).default(5000),
  VTEX_MAX_RETRIES: Joi.number().integer().min(0).default(2),
  VTEX_RETRY_DELAY_MS: Joi.number().integer().min(0).default(250),
  VTEX_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  VTEX_DEFAULT_CURRENCY: Joi.string().default('COP'),
  VTEX_INCLUDE_SHIPPING: Joi.boolean().truthy('true').falsy('false').default(false),
  VTEX_SECONDARY_APP_KEY: Joi.string().allow('').optional(),
  VTEX_SECONDARY_APP_TOKEN: Joi.string().allow('').optional(),
  VTEX_CREDENTIALS: Joi.string().allow('').optional(),
  METRICS_ENABLED: Joi.boolean().truthy('true').truthy('1').falsy('false').falsy('0').default(true),
  METRICS_API_KEY: Joi.string().allow('').optional(),
  MAIL_ENABLED: Joi.boolean().truthy('true').truthy('1').falsy('false').falsy('0').default(true),
  MAIL_TRANSPORT: Joi.string().valid('smtp', 'stream', 'memory').optional(),
  MAIL_FROM: Joi.string().allow('').optional(),
  MAIL_ALERT_GLOBAL: Joi.string().allow('').optional(),
  MAIL_ALERT_FINANCE: Joi.string().allow('').optional(),
  MAIL_ALERT_OPERATIONS: Joi.string().allow('').optional(),
  MAIL_SMTP_HOST: Joi.string().allow('').optional(),
  MAIL_SMTP_PORT: Joi.number().integer().min(1).max(65535).optional(),
  MAIL_SMTP_SECURE: Joi.boolean().truthy('true').truthy('1').falsy('false').falsy('0').optional(),
  MAIL_SMTP_USER: Joi.string().allow('').optional(),
  MAIL_SMTP_PASS: Joi.string().allow('').optional(),
  OTEL_SERVICE_NAME: Joi.string().allow('').optional(),
  OTEL_EXPORTER_OTLP_ENDPOINT: Joi.string().allow('').optional()
});
