global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: /api/v1/metrics
    static_configs:
      - targets:
          - api:3001
  - job_name: 'worker'
    metrics_path: /metrics
    static_configs:
      - targets:
          - worker:9465
